Automatically set rao-relative-margins-parameters::ptdf-boundaries parameter based on F327 (virtualhubs) file content
farao-community/gridcapa-core-cc pull request #68
Opened 2024-04-04 08:39 UTC by vbochetRTE

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2024-04-08 13:13 UTC, danielthirion commented on pom.xml
> +        <farao.dependencies.version>1.28.0-SNAPSHOT</farao.dependencies.version>
farao dependencies 1.28.0 has now been released, either use it or switch to 1.29.0-SNAPSHOT for testing purposes

2024-04-08 13:38 UTC, danielthirion approved these changes

2024-04-16 08:38 UTC, kahyami requested changes

2024-04-16 08:38 UTC, kahyami commented on gridcapa-core-cc-app/src/test/java/com/farao_community/farao/gridcapa_core_cc/app/preprocessing/RaoParametersServiceTest.java
> +        virtualHubsConfiguration.addMarketArea(new MarketArea("FR", "10YFR-RTE------C", true, false));
Given the duplication of the country and the eic in several tests, i propose that we declare this variable as constant.

2024-04-16 11:15 UTC, merged